import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import Compositor from "@/components/display/compositor";
import { cn } from "@/lib/utils";
import { RootStoreProvider } from "@/providers/store-provider";
import ThemeProvider from "@/providers/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--poppins-font",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", poppins.className)}>
        <RootStoreProvider>
          <ThemeProvider>
            <Compositor>{children}</Compositor>
          </ThemeProvider>
        </RootStoreProvider>
      </body>
    </html>
  );
}
